// src/nextjs/client/SeatmapCanvas.tsx
/*
 * SeatmapCanvas.tsx
 * Next.js Client Component for Seatmap Canvas
 * This component uses 'use client' directive for browser-only features
 */

'use client';

import React, { useEffect, useRef, useImperativeHandle, forwardRef, useState } from 'react';
import { SeatMapCanvas } from '../../lib/canvas.index';
import type { SeatmapCanvasProps, SeatmapCanvasRef } from '../types';

const SeatmapCanvasComponent = forwardRef<SeatmapCanvasRef, SeatmapCanvasProps>(
  (
    {
      options = {},
      data = [],
      className = '',
      style = {},
      autoZoomToVenue = true,
      onReady,
      onSeatClick,
      onSeatSelect,
      onSeatUnselect,
      onBlockClick,
      onDataChange,
    },
    ref
  ) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const seatmapRef = useRef<SeatMapCanvas | null>(null);
    const [mounted, setMounted] = useState(false);
    const eventHandlersRef = useRef({
      onSeatClick,
      onSeatSelect,
      onSeatUnselect,
      onBlockClick,
    });

    // Update event handlers ref when props change
    useEffect(() => {
      eventHandlersRef.current = {
        onSeatClick,
        onSeatSelect,
        onSeatUnselect,
        onBlockClick,
      };
    }, [onSeatClick, onSeatSelect, onSeatUnselect, onBlockClick]);

    // Handle client-side mounting to prevent hydration mismatches
    useEffect(() => {
      setMounted(true);
    }, []);

    // Initialize seatmap only after component is mounted (client-side only)
    useEffect(() => {
      if (!mounted || !containerRef.current) return;

      // Initialize Seatmap Canvas
      seatmapRef.current = new SeatMapCanvas(containerRef.current, options);

      // Setup event listeners
      if (seatmapRef.current) {
        const instance = seatmapRef.current;

        instance.eventManager.addEventListener('SEAT.CLICK', (seat: any) => {
          if (eventHandlersRef.current.onSeatClick) {
            eventHandlersRef.current.onSeatClick(seat);
          }
        });

        instance.eventManager.addEventListener('SEAT.SELECT', (seat: any) => {
          if (eventHandlersRef.current.onSeatSelect) {
            eventHandlersRef.current.onSeatSelect(seat);
          }
        });

        instance.eventManager.addEventListener('SEAT.UNSELECT', (seat: any) => {
          if (eventHandlersRef.current.onSeatUnselect) {
            eventHandlersRef.current.onSeatUnselect(seat);
          }
        });

        instance.eventManager.addEventListener('BLOCK.CLICK', (block: any) => {
          if (eventHandlersRef.current.onBlockClick) {
            eventHandlersRef.current.onBlockClick(block);
          }
        });

        // Load initial data
        if (data && data.length > 0) {
          instance.data.replaceData(data);
          if (autoZoomToVenue) {
            setTimeout(() => {
              instance.zoomManager.zoomToVenue();
            }, 100);
          }
        }

        // Call onReady callback
        if (onReady) {
          onReady(instance);
        }
      }

      // Cleanup
      return () => {
        seatmapRef.current = null;
      };
    }, [mounted, options]); // Only run once after mount

    // Watch for data changes
    useEffect(() => {
      if (!mounted) return;
      
      if (seatmapRef.current && data && data.length > 0) {
        seatmapRef.current.data.replaceData(data);
        if (autoZoomToVenue) {
          setTimeout(() => {
            seatmapRef.current?.zoomManager.zoomToVenue();
          }, 100);
        }
        if (onDataChange) {
          onDataChange(data);
        }
      }
    }, [data, autoZoomToVenue, onDataChange, mounted]);

    // Expose methods via ref
    useImperativeHandle(ref, () => ({
      getInstance: () => seatmapRef.current,
      seatmap: seatmapRef.current,
    }));

    // Show skeleton/placeholder during SSR and initial client render
    if (!mounted) {
      return (
        <div
          className={className}
          style={{
            width: '100%',
            height: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#f5f5f5',
            ...style,
          }}
        >
          <div
            style={{
              width: '40px',
              height: '40px',
              border: '4px solid #e0e0e0',
              borderTop: '4px solid #666',
              borderRadius: '50%',
              animation: 'spin 1s linear infinite',
            }}
          />
          <style>{`
            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }
          `}</style>
        </div>
      );
    }

    return (
      <div
        ref={containerRef}
        className={className}
        style={{ width: '100%', height: '100%', ...style }}
      />
    );
  }
);

SeatmapCanvasComponent.displayName = 'SeatmapCanvas';

export default SeatmapCanvasComponent;

// src/vue/SeatmapCanvas.vue
<template>
  <div ref="containerRef" :class="containerClass" :style="containerStyle"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, computed } from 'vue';
import { SeatMapCanvas } from '../lib/canvas.index';
import type { SeatmapOptions, BlockData } from './types';

export interface Props {
  options?: SeatmapOptions;
  data?: BlockData[];
  containerClass?: string;
  containerStyle?: Record<string, string>;
  autoZoomToVenue?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  options: () => ({}),
  data: () => [],
  containerClass: '',
  containerStyle: () => ({}),
  autoZoomToVenue: true,
});

const emit = defineEmits<{
  ready: [instance: SeatMapCanvas];
  seatClick: [seat: any];
  seatSelect: [seat: any];
  seatUnselect: [seat: any];
  blockClick: [block: any];
  dataChange: [data: BlockData[]];
}>();

const containerRef = ref<HTMLElement | null>(null);
const seatmapInstance = ref<SeatMapCanvas | null>(null);

const getInstance = () => seatmapInstance.value;

// Watch for data changes
watch(
  () => props.data,
  (newData) => {
    if (seatmapInstance.value && newData && newData.length > 0) {
      seatmapInstance.value.data.replaceData(newData);
      if (props.autoZoomToVenue) {
        setTimeout(() => {
          seatmapInstance.value?.zoomManager.zoomToVenue();
        }, 100);
      }
      emit('dataChange', newData);
    }
  },
  { deep: true }
);

onMounted(() => {
  if (!containerRef.value) return;

  // Initialize Seatmap Canvas
  seatmapInstance.value = new SeatMapCanvas(containerRef.value, props.options);

  // Setup event listeners
  if (seatmapInstance.value) {
    seatmapInstance.value.eventManager.addEventListener('SEAT.CLICK', (seat: any) => {
      emit('seatClick', seat);
    });

    seatmapInstance.value.eventManager.addEventListener('SEAT.SELECT', (seat: any) => {
      emit('seatSelect', seat);
    });

    seatmapInstance.value.eventManager.addEventListener('SEAT.UNSELECT', (seat: any) => {
      emit('seatUnselect', seat);
    });

    seatmapInstance.value.eventManager.addEventListener('BLOCK.CLICK', (block: any) => {
      emit('blockClick', block);
    });

    // Load initial data
    if (props.data && props.data.length > 0) {
      seatmapInstance.value.data.replaceData(props.data);
      if (props.autoZoomToVenue) {
        setTimeout(() => {
          seatmapInstance.value?.zoomManager.zoomToVenue();
        }, 100);
      }
    }

    emit('ready', seatmapInstance.value);
  }
});

onBeforeUnmount(() => {
  // Cleanup if needed
  seatmapInstance.value = null;
});

defineExpose({
  getInstance,
  seatmap: computed(() => seatmapInstance.value),
});
</script>

<style scoped>
div {
  width: 100%;
  height: 100%;
}
</style>
